### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by brianpenghe** [SamuelHLewis/sRNAplot#4]
I ran this:
`python sRNAplot.py -s Samplename -i ~/Samplename.bam -m 23 -M 29 --pingpong --distribution
`
But I got this error message:
`Traceback (most recent call last):
  File "sRNAplot.py", line 833, in <module>
    fiveprime_host = bam_5prime_stranded(file=InFile,minlength=MinLength,maxlength=MaxLength,unique=Unique)
  File "sRNAplot.py", line 381, in bam_5prime_stranded
    count = int(linesplit[0].split('-')[1])
IndexError: list index out of range`

Any thoughts?

**Comment by SamuelHLewis** [comment]
This might be caused by the name formatting of your read file. They should be labelled in the form:

>readname-readcount

This is the format that fastx_collapser from the [FASTX toolkit](http://hannonlab.cshl.edu/fastx_toolkit/) produces. Did you collapse your small RNA reads before mapping them?

**Comment by brianpenghe** [comment]
> This might be caused by the name formatting of your read file. They should be labelled in the form:
> 
> > readname-readcount
> 
> This is the format that fastx_collapser from the [FASTX toolkit](http://hannonlab.cshl.edu/fastx_toolkit/) produces. Did you collapse your small RNA reads before mapping them?

No I didn't collapse the fastq files before mapping. The reason is that a lot of downstream analyses need a bam file that hasn't had the fastq reads collapsed : (
